# Generated by Django 3.2.25 on 2026-01-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Video File')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', verbose_name='Thumbnail')),
                ('duration', models.DurationField(blank=True, help_text='e.g. 00:05:30', null=True, verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instructional Video',
                'verbose_name_plural': 'Instructional Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
